language: generic

sudo: required
servies:
  - docker
before_install:
  - docker build -t mehul2205/react -f Dockerfile.dev .

script:
  - docker run -e CI=true mehul2205/react npm run test

deploy:
  provider: heroku
  api_key:
    secure: ${process.env.SECRET_KEY}
  app: mehul2205-react-app-docker
  on:
    branch: master