# Base Image
FROM node:16-alpine

# ENV CHOKIDAR_USEPOLLING=true

WORKDIR /usr/mehul2205/project3
# Installations
COPY package.json .
RUN npm install
COPY . .

# CMD
CMD [ "npm", "run", "start" ]